### ISSUE TITLE
Keybindings to run a program

### ISSUE THREAD

**Issue by yssoe** [ets-labs/vimrc#23]
HI, this .vimrc works awesomely good on my arch linux with i3wm. 

I just can't find how the keybindings work to run the python file? What would be the best way to just run the python file I'm working in. 

Sorry for that idiotic question. 

Cheers

**Comment by rmk135** [comment]
Hey Yves,

It's so nice to hear such warm comments. Hopefully, you will enjoy it in future as well.

Regarding the feature of running python files - unfortunately, there is no such binding in config for now. At the same time, I would be pleased to add it. So, will keep you on track...

Thanks,
Roman

**Comment by rmk135** [comment]
Feature was committed in 84193d2e7718c3941281f60c9b177a4d57b891fd. Now we can press `<F5>` for running code from buffer.

Yves, you can update your local configuration by pulling latest from remote repo: `cd ~/.vim && git fetch && git rebase origin/master`

**Comment by yssoe** [comment]
Hi works perfectly!! Thanks.

**Comment by rmk135** [comment]
Cool! U're welcome ;)

**Comment by yssoe** [comment]
```
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

```

I also use these keys to jump around from window to window, does that makes sense? I've added this to the bottom of .vimrc 

Somebody might like this too. 

Cheers

**Comment by rmk135** [comment]
Hey Yves,

Yeah, it definitely makes sense! At the same time, I tend think about such things as individual configuration and leave it to the user's judgement. One thing that we can (perhaps, even need to) do is to specify a way how users can add their personal settings leaving main .vimrc clear (and updatable).

Roman
