### ISSUE TITLE
Font issue on Mac OS X El Capitan

### ISSUE THREAD

**Issue by Tset-Noitamotua** [ets-labs/vimrc#25]
Are special fonts required for Mac OS X? Which?

![image](https://cloud.githubusercontent.com/assets/5635462/21266269/99386914-c3a5-11e6-8a54-79ba9c16837a.png)

Cheers
Tset

**Comment by rmk135** [comment]
Hello Tset,

I think that you're looking for powerline fonts - https://github.com/powerline/fonts

Short googling about installation of powerline fonts on mac gave me this - https://coderwall.com/p/yiot4q/setup-vim-powerline-and-iterm2-on-mac-os-x

Hope it helps,
Thanks,
Roman

**Comment by Tset-Noitamotua** [comment]
Thank you! Works!

Especially the second link is very useful.

**Comment by rmk135** [comment]
U're welcome ;)
