### ISSUE TITLE
autocompletion plugin: Jedi-Vim vs. YouCompleteMe

### ISSUE THREAD

**Issue by Tset-Noitamotua** [ets-labs/vimrc#26]
Why have you picked 'davidhalter/jedi-vim' plugin for autocompletion? Is it the best one?

I would like to try '[Valloric/YouCompleteMe](https://github.com/Valloric/YouCompleteMe)' but I never managed to make it work (ok, I was on Windows as I tried). May be I'll have more luck on a mac now :)

**Comment by rmk135** [comment]
Hey Tset,

I've looked on YouCompleteMe and decided to experiment with it for a couple of days... What's about your experience? Have you already install it?

Roman

**Comment by rmk135** [comment]
Hello Tset,

I've updated configuration to use YouCompleteMe, it's cool indeed.

Thanks,
Roman

**Comment by Tset-Noitamotua** [comment]
I haven't try yet  ... but now I'll give it a go, too :)

**Comment by Tset-Noitamotua** [comment]
not sure do I need to install YCM first and then run your installation script `sh -c "$(curl -fsSL ... )`?

**Comment by Tset-Noitamotua** [comment]
ok I figured it out ...

1. run `sh -c "$(curl -fsSL https://raw.githubusercontent.com/ets-labs/python-vimrc/master/setup.sh)"`

2. run `~/.vim/bundle/YouCompleteMe/install.py --clang-completer`

3. enjoy ...

![image](https://cloud.githubusercontent.com/assets/5635462/21459054/8b86e084-c93b-11e6-8abd-5a25977c5dfc.png)

**Comment by Tset-Noitamotua** [comment]
It's so cool. Thank you so much!!!

bwt. Do you know if YCM can be configured to show docstring along with autocompletion?
