### ISSUE TITLE
omnicomplete still in .vimrc

### ISSUE THREAD

**Issue by Tset-Noitamotua** [ets-labs/vimrc#27]
Now that you configured to use YCM for autocompletion shouldn't you remove things related to omnicomplete like lines below?

```
" omnicomplete
set completeopt-=preview                    " remove omnicompletion dropdown
```

**Comment by rmk135** [comment]
Hey Tset,

I've checked this option and found that it's been useful to me. It prevents opening of a buffer with docblock in the top of the central buffer, that I don't like, to be honest...

So, I plan to leave it in current configuration. Also I've moved it to the YCM configuration section for keeping it closer to autocompletion functionality configuration.

Thansk,
Roman

**Comment by Tset-Noitamotua** [comment]
I agree the docstring block is a bit annoying.
