### ISSUE TITLE
The Red Line in Right side of the terminal.

### ISSUE THREAD

**Issue by aasutossh** [ets-labs/vimrc#30]
How to deal with the red vertical line appearing in right side of the terminal.

**Comment by rmk135** [comment]
Hi @AJgotBeard ,

What do you want to make with it? Do you want to remove it completely or move it left?

Thanks,
Roman

**Comment by aasutossh** [comment]
I wanted it to be gone actually.

**Comment by aasutossh** [comment]
Sorry about this issue being open for too long.

**Comment by Yashvendra** [comment]
Hi, you can convert that to gray by adding the following line in your `.vimrc`.
```$
hi ColorColumn ctermbg=8
````
