### ISSUE TITLE
pymode_doc_key name changed to pymode_doc_bind in 0.7.8b

### ISSUE THREAD

**Issue by alphaCTzo7G** [ets-labs/vimrc#33]
Hi

In this line, it uses pymode_doc_key: 
https://github.com/ets-labs/python-vimrc/blob/ab61240211959ae171c8b4f46c5f1153734bb803/vimrc#L169

However, python-mode has change the variable name pymode_doc_key to pymode_doc_bind in version 0.7.8b (https://github.com/python-mode/python-mode/blob/b848f6294ca5858fd17eaf14783fa2042e8142b7/Changelog.rst#L81). 

Would you it be ok, if I do a PR to update the variable?

**Comment by rmk135** [comment]
Hi there,

Yeah, definitely! Please, go ahead!

... Didn't know about this. I would merge it ASAP.

Thanks a lot,
Roman

**Comment by rmk135** [comment]
Hi @alphaCTzo7G ,

How are you? Just wanted to ask you if you still plan to propose PR for fixing this problem?

Thanks,
Roman

**Comment by rmk135** [comment]
Fixed in https://github.com/ets-labs/python-vimrc/commit/18574648b741e571cdfc29340b7e3e2ee03e2400.
