### ISSUE TITLE
Cannot close only one tab when opening several files

### ISSUE THREAD

**Issue by Shawn-Guo-CN** [ets-labs/vimrc#36]
When I open several files in one tab, I cannot close the active tab but keep the others opened. How could I do that?

For example, when I open 'train.py' and 'data.py' at the same time, once I `wq` 'train.py', the vim shutdown totally. But, I still want to edit 'data.py'. I'm new to vim, how could I get this?

**Comment by rmk135** [comment]
Hey @Air-Fighter ,

I think you can try `\q`.

**Comment by Shawn-Guo-CN** [comment]
It works, thank you @rmk135
