### ISSUE TITLE
Improve setup script

### ISSUE THREAD

**Issue by rmk135** [ets-labs/vimrc#8]
Make it like homebrew does:

``` bash
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

**Comment by boonya** [comment]
Or zsh ;)
https://github.com/robbyrussell/oh-my-zsh#basic-installation
It's better for us because we do not use ruby.

**Comment by rmk135** [comment]
What do you think if will keep shell? I propose to do something like this:

```bash
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
```

**Comment by rmk135** [comment]
Yeah, right! :+1:

**Comment by boonya** [comment]
It is the best solution imo
